2025-09-23 13:32:28 | INFO | === Logger initialized ===
2025-09-23 13:32:28 | INFO | [MONITOR][START] poll=1.0s
2025-09-23 13:32:28 | INFO | [SCANNER][START] delay=2.5s parallel=True workers=6
2025-09-23 13:32:32 | WARNING | [PRED][DEEPar][ERR] LINEAUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:32:32 | WARNING | [PRED][DEEPar][ERR] AIAUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:32:32 | WARNING | [PRED][DEEPar][ERR] STBLUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:32:32 | WARNING | [PRED][DEEPar][ERR] BARDUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:32:32 | WARNING | [PRED][DEEPar][ERR] 0GUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:32:36 | WARNING | [PRED][DEEPar][ERR] BARDUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:32:36 | WARNING | [PRED][DEEPar][ERR] LINEAUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:32:36 | WARNING | [PRED][DEEPar][ERR] ASTERUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:32:36 | WARNING | [PRED][DEEPar][ERR] 0GUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:32:36 | ERROR | [ENTER][ERR] AIAUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:32:36 | ERROR | [ENTER][ERR] STBLUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:32:36 | ERROR | [ENTER][ERR] LINEAUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:32:36 | ERROR | [ENTER][ERR] 0GUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:32:36 | ERROR | [ENTER][ERR] BARDUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:32:36 | ERROR | [ENTER][ERR] ASTERUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:32:38 | WARNING | [PRED][DEEPar][ERR] OPENUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:32:39 | WARNING | [PRED][DEEPar][ERR] OPENUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:32:39 | ERROR | [ENTER][ERR] OPENUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:32:39 | ERROR | [ENTER][ERR] SOMIUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:32:39 | ERROR | [ENTER][ERR] UBUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:32:45 | WARNING | [PRED][DEEPar][ERR] LINEAUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:32:45 | WARNING | [PRED][DEEPar][ERR] ASTERUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:32:48 | WARNING | [PRED][DEEPar][ERR] ASTERUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:32:48 | WARNING | [PRED][DEEPar][ERR] LINEAUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:32:48 | ERROR | [ENTER][ERR] STBLUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:32:48 | ERROR | [ENTER][ERR] ASTERUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:32:48 | ERROR | [ENTER][ERR] LINEAUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:32:48 | ERROR | [ENTER][ERR] BARDUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:32:48 | ERROR | [ENTER][ERR] 0GUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:32:48 | ERROR | [ENTER][ERR] AIAUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:32:50 | WARNING | [PRED][DEEPar][ERR] UBUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:32:50 | WARNING | [PRED][DEEPar][ERR] OPENUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:32:51 | WARNING | [PRED][DEEPar][ERR] UBUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:32:51 | WARNING | [PRED][DEEPar][ERR] OPENUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:32:51 | ERROR | [ENTER][ERR] SOMIUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:32:51 | ERROR | [ENTER][ERR] OPENUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:32:51 | ERROR | [ENTER][ERR] UBUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:32:57 | WARNING | [PRED][DEEPar][ERR] 0GUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:33:03 | WARNING | [PRED][DEEPar][ERR] 0GUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:33:03 | WARNING | [PRED][DEEPar][ERR] BARDUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:33:03 | ERROR | [ENTER][ERR] AIAUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:33:03 | ERROR | [ENTER][ERR] ASTERUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:33:03 | ERROR | [ENTER][ERR] STBLUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:33:03 | ERROR | [ENTER][ERR] BARDUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:33:03 | ERROR | [ENTER][ERR] 0GUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:33:03 | ERROR | [ENTER][ERR] LINEAUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:33:06 | WARNING | [PRED][DEEPar][ERR] OPENUSDT -> CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

2025-09-23 13:33:08 | WARNING | [PRED][DEEPar][ERR] SOMIUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:33:08 | ERROR | [ENTER][ERR] UBUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:33:08 | ERROR | [ENTER][ERR] SOMIUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:33:08 | ERROR | [ENTER][ERR] OPENUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:33:15 | WARNING | [PRED][DEEPar][ERR] ASTERUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:33:15 | WARNING | [PRED][DEEPar][ERR] LINEAUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:33:15 | WARNING | [PRED][DEEPar][ERR] 0GUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:33:18 | WARNING | [PRED][DEEPar][ERR] 0GUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:33:18 | WARNING | [PRED][DEEPar][ERR] LINEAUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:33:18 | ERROR | [ENTER][ERR] AIAUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:33:18 | ERROR | [ENTER][ERR] STBLUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:33:18 | ERROR | [ENTER][ERR] 0GUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:33:18 | ERROR | [ENTER][ERR] BARDUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:33:18 | ERROR | [ENTER][ERR] LINEAUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:33:18 | ERROR | [ENTER][ERR] ASTERUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:33:22 | WARNING | [PRED][DEEPar][ERR] OPENUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:33:22 | WARNING | [PRED][DEEPar][ERR] UBUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:33:24 | WARNING | [PRED][DEEPar][ERR] SOMIUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:33:24 | WARNING | [PRED][DEEPar][ERR] UBUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:33:24 | ERROR | [ENTER][ERR] OPENUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:33:24 | ERROR | [ENTER][ERR] SOMIUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:33:24 | ERROR | [ENTER][ERR] UBUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:33:35 | WARNING | [PRED][DEEPar][ERR] AIAUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:33:35 | WARNING | [PRED][DEEPar][ERR] STBLUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:33:35 | WARNING | [PRED][DEEPar][ERR] ASTERUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:33:35 | WARNING | [PRED][DEEPar][ERR] 0GUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:33:35 | ERROR | [ENTER][ERR] LINEAUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:33:35 | ERROR | [ENTER][ERR] BARDUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:33:35 | ERROR | [ENTER][ERR] ASTERUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:33:35 | ERROR | [ENTER][ERR] 0GUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:33:35 | ERROR | [ENTER][ERR] AIAUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:33:35 | ERROR | [ENTER][ERR] STBLUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_book_ticker(symbol=symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:33:37 | WARNING | [PRED][DEEPar][ERR] OPENUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:33:37 | WARNING | [PRED][DEEPar][ERR] SOMIUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:33:40 | WARNING | [PRED][DEEPar][ERR] OPENUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:33:40 | WARNING | [PRED][DEEPar][ERR] UBUSDT -> Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
2025-09-23 13:33:40 | ERROR | [ENTER][ERR] UBUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_order_book(symbol=symbol, limit=5)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:33:40 | ERROR | [ENTER][ERR] OPENUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_order_book(symbol=symbol, limit=5)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:33:40 | ERROR | [ENTER][ERR] SOMIUSDT -> 'Client' object has no attribute 'futures_book_ticker'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 649, in try_enter
    bid, ask, mid = get_quote(symbol)
                    ^^^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 184, in get_quote
    ob = client.futures_order_book(symbol=symbol, limit=5)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'futures_book_ticker'
2025-09-23 13:33:44 | INFO | === Logger initialized ===
2025-09-23 13:33:44 | INFO | [MONITOR][START] poll=1.0s
2025-09-23 13:33:44 | INFO | [SCANNER][START] delay=2.5s parallel=True workers=6
2025-09-23 13:34:05 | INFO | === Logger initialized ===
2025-09-23 13:34:05 | INFO | [MONITOR][START] poll=1.0s
2025-09-23 13:34:05 | INFO | [SCANNER][START] delay=2.5s parallel=True workers=6
2025-09-23 13:34:11 | INFO | [ENTER][PREP] ASTERUSDT side=Buy conf=1.00 mid=1.591850 qty=124.0
2025-09-23 13:34:11 | INFO | [ENTER][PREP] 0GUSDT side=Buy conf=1.00 mid=6.045100 qty=33.0
2025-09-23 13:34:11 | INFO | [ENTER][POSTONLY] ASTERUSDT side=Buy qty=124.0 px=1.5918 oid=247207260
2025-09-23 13:34:11 | INFO | [ENTER][PREP] LINEAUSDT side=Sell conf=1.00 mid=0.026815 qty=7336.0
2025-09-23 13:34:11 | INFO | [ENTER][PREP] STBLUSDT side=Buy conf=1.00 mid=0.338915 qty=581.0
2025-09-23 13:34:11 | INFO | [ENTER][PREP] BARDUSDT side=Buy conf=1.00 mid=1.023050 qty=193.0
2025-09-23 13:34:11 | INFO | [ENTER][PREP] AIAUSDT side=Sell conf=1.00 mid=0.292480 qty=673.0
2025-09-23 13:34:11 | WARNING | [ORDER][REJECT] 0GUSDT Buy -> Due to the order could not be executed as maker, the Post Only order will be rejected. The order will not be recorded in the order history
2025-09-23 13:34:11 | WARNING | [ENTER][POSTONLY][FAIL] 0GUSDT side=Buy qty=33.0
2025-09-23 13:34:11 | WARNING | [ORDER][REJECT] LINEAUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:34:11 | WARNING | [ENTER][POSTONLY][FAIL] LINEAUSDT side=Sell qty=7336.0
2025-09-23 13:34:12 | WARNING | [ORDER][REJECT] STBLUSDT Buy -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:34:12 | WARNING | [ENTER][POSTONLY][FAIL] STBLUSDT side=Buy qty=581.0
2025-09-23 13:34:12 | WARNING | [ORDER][REJECT] BARDUSDT Buy -> Due to the order could not be executed as maker, the Post Only order will be rejected. The order will not be recorded in the order history
2025-09-23 13:34:12 | WARNING | [ENTER][POSTONLY][FAIL] BARDUSDT side=Buy qty=193.0
2025-09-23 13:34:12 | WARNING | [ORDER][REJECT] AIAUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:34:12 | WARNING | [ENTER][POSTONLY][FAIL] AIAUSDT side=Sell qty=673.0
2025-09-23 13:34:13 | INFO | [POSTONLY][FILLED/REMOVED] ASTERUSDT oid=247207260
2025-09-23 13:34:13 | ERROR | [MONITOR][ERR] set_stop_with_retry() got an unexpected keyword argument 'close_side'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 872, in monitor_loop
    set_stop_with_retry(sym, sl_price=sl, tp_price=tp3, close_side=close_side)
TypeError: set_stop_with_retry() got an unexpected keyword argument 'close_side'
2025-09-23 13:34:15 | INFO | [ENTER][PREP] SOMIUSDT side=Sell conf=1.00 mid=0.899950 qty=219.0
2025-09-23 13:34:15 | INFO | [ENTER][POSTONLY] SOMIUSDT side=Sell qty=219.0 px=0.9 oid=810838426
2025-09-23 13:34:15 | INFO | [ENTER][PREP] UBUSDT side=Sell conf=1.00 mid=0.033683 qty=5841.0
2025-09-23 13:34:15 | INFO | [ENTER][PREP] OPENUSDT side=Sell conf=1.00 mid=0.719650 qty=274.0
2025-09-23 13:34:15 | WARNING | [ORDER][REJECT] UBUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:34:15 | WARNING | [ENTER][POSTONLY][FAIL] UBUSDT side=Sell qty=5841.0
2025-09-23 13:34:15 | ERROR | [MONITOR][ERR] set_stop_with_retry() got an unexpected keyword argument 'close_side'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 872, in monitor_loop
    set_stop_with_retry(sym, sl_price=sl, tp_price=tp3, close_side=close_side)
TypeError: set_stop_with_retry() got an unexpected keyword argument 'close_side'
2025-09-23 13:34:15 | INFO | [ENTER][POSTONLY] OPENUSDT side=Sell qty=274.0 px=0.7197 oid=312506992
2025-09-23 13:34:17 | WARNING | [ORDER][REJECT] ASTERUSDT Sell -> ReduceOnly Order is rejected.
2025-09-23 13:34:17 | ERROR | [MONITOR][ERR] set_stop_with_retry() got an unexpected keyword argument 'close_side'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 872, in monitor_loop
    set_stop_with_retry(sym, sl_price=sl, tp_price=tp3, close_side=close_side)
TypeError: set_stop_with_retry() got an unexpected keyword argument 'close_side'
2025-09-23 13:34:20 | WARNING | [ORDER][REJECT] ASTERUSDT Sell -> ReduceOnly Order is rejected.
2025-09-23 13:34:20 | WARNING | [ORDER][REJECT] ASTERUSDT Sell -> ReduceOnly Order is rejected.
2025-09-23 13:34:20 | ERROR | [MONITOR][ERR] set_stop_with_retry() got an unexpected keyword argument 'close_side'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 872, in monitor_loop
    set_stop_with_retry(sym, sl_price=sl, tp_price=tp3, close_side=close_side)
TypeError: set_stop_with_retry() got an unexpected keyword argument 'close_side'
2025-09-23 13:34:22 | WARNING | [ORDER][REJECT] ASTERUSDT Sell -> ReduceOnly Order is rejected.
2025-09-23 13:34:22 | WARNING | [ORDER][REJECT] ASTERUSDT Sell -> ReduceOnly Order is rejected.
2025-09-23 13:34:22 | ERROR | [MONITOR][ERR] set_stop_with_retry() got an unexpected keyword argument 'close_side'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 872, in monitor_loop
    set_stop_with_retry(sym, sl_price=sl, tp_price=tp3, close_side=close_side)
TypeError: set_stop_with_retry() got an unexpected keyword argument 'close_side'
2025-09-23 13:34:24 | INFO | [ENTER][PREP] LINEAUSDT side=Sell conf=1.00 mid=0.026765 qty=7350.0
2025-09-23 13:34:24 | INFO | [ENTER][PREP] BARDUSDT side=Buy conf=1.00 mid=1.023950 qty=193.0
2025-09-23 13:34:24 | INFO | [ENTER][PREP] AIAUSDT side=Sell conf=1.00 mid=0.292375 qty=673.0
2025-09-23 13:34:24 | INFO | [ENTER][PREP] STBLUSDT side=Buy conf=1.00 mid=0.339055 qty=581.0
2025-09-23 13:34:24 | INFO | [ENTER][PREP] 0GUSDT side=Buy conf=1.00 mid=6.004450 qty=33.0
2025-09-23 13:34:24 | INFO | [ENTER][PREP] UBUSDT side=Sell conf=1.00 mid=0.033661 qty=5844.0
2025-09-23 13:34:24 | WARNING | [ORDER][REJECT] LINEAUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:34:24 | WARNING | [ENTER][POSTONLY][FAIL] LINEAUSDT side=Sell qty=7350.0
2025-09-23 13:34:24 | INFO | [ENTER][POSTONLY] BARDUSDT side=Buy qty=193.0 px=1.0239 oid=107002442
2025-09-23 13:34:24 | INFO | [POSTONLY][FILLED/REMOVED] SOMIUSDT oid=810838426
2025-09-23 13:34:24 | WARNING | [ORDER][REJECT] AIAUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:34:24 | WARNING | [ENTER][POSTONLY][FAIL] AIAUSDT side=Sell qty=673.0
2025-09-23 13:34:24 | ERROR | [MONITOR][ERR] set_stop_with_retry() got an unexpected keyword argument 'close_side'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 872, in monitor_loop
    set_stop_with_retry(sym, sl_price=sl, tp_price=tp3, close_side=close_side)
TypeError: set_stop_with_retry() got an unexpected keyword argument 'close_side'
2025-09-23 13:34:24 | WARNING | [ORDER][REJECT] STBLUSDT Buy -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:34:24 | WARNING | [ENTER][POSTONLY][FAIL] STBLUSDT side=Buy qty=581.0
2025-09-23 13:34:25 | INFO | [ENTER][POSTONLY] 0GUSDT side=Buy qty=33.0 px=6.0044 oid=221693756
2025-09-23 13:34:25 | WARNING | [ORDER][REJECT] UBUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:34:25 | WARNING | [ENTER][POSTONLY][FAIL] UBUSDT side=Sell qty=5844.0
2025-09-23 13:34:26 | INFO | [POSTONLY][FILLED/REMOVED] BARDUSDT oid=107002442
2025-09-23 13:34:27 | ERROR | [MONITOR][ERR] set_stop_with_retry() got an unexpected keyword argument 'close_side'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 872, in monitor_loop
    set_stop_with_retry(sym, sl_price=sl, tp_price=tp3, close_side=close_side)
TypeError: set_stop_with_retry() got an unexpected keyword argument 'close_side'
2025-09-23 13:34:29 | INFO | [POSTONLY][FILLED/REMOVED] OPENUSDT oid=312506992
2025-09-23 13:34:29 | INFO | [POSTONLY][FILLED/REMOVED] 0GUSDT oid=221693756
2025-09-23 13:34:29 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:34:29 | ERROR | [MONITOR][ERR] set_stop_with_retry() got an unexpected keyword argument 'close_side'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 872, in monitor_loop
    set_stop_with_retry(sym, sl_price=sl, tp_price=tp3, close_side=close_side)
TypeError: set_stop_with_retry() got an unexpected keyword argument 'close_side'
2025-09-23 13:34:31 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:34:31 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:34:31 | ERROR | [MONITOR][ERR] set_stop_with_retry() got an unexpected keyword argument 'close_side'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 872, in monitor_loop
    set_stop_with_retry(sym, sl_price=sl, tp_price=tp3, close_side=close_side)
TypeError: set_stop_with_retry() got an unexpected keyword argument 'close_side'
2025-09-23 13:34:32 | INFO | [ENTER][PREP] STBLUSDT side=Buy conf=1.00 mid=0.339130 qty=583.0
2025-09-23 13:34:32 | INFO | [ENTER][PREP] AIAUSDT side=Sell conf=1.00 mid=0.292745 qty=676.0
2025-09-23 13:34:32 | INFO | [ENTER][PREP] UBUSDT side=Sell conf=1.00 mid=0.033698 qty=5865.0
2025-09-23 13:34:32 | INFO | [ENTER][PREP] ASTERUSDT side=Buy conf=1.00 mid=1.601950 qty=124.0
2025-09-23 13:34:32 | INFO | [ENTER][PREP] LINEAUSDT side=Sell conf=1.00 mid=0.026785 qty=7378.0
2025-09-23 13:34:32 | WARNING | [ORDER][REJECT] STBLUSDT Buy -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:34:32 | WARNING | [ENTER][POSTONLY][FAIL] STBLUSDT side=Buy qty=583.0
2025-09-23 13:34:32 | WARNING | [ORDER][REJECT] AIAUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:34:32 | WARNING | [ENTER][POSTONLY][FAIL] AIAUSDT side=Sell qty=676.0
2025-09-23 13:34:33 | WARNING | [ORDER][REJECT] UBUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:34:33 | WARNING | [ENTER][POSTONLY][FAIL] UBUSDT side=Sell qty=5865.0
2025-09-23 13:34:33 | WARNING | [ORDER][REJECT] ASTERUSDT Buy -> Margin is insufficient.
2025-09-23 13:34:33 | WARNING | [ENTER][POSTONLY][FAIL] ASTERUSDT side=Buy qty=124.0
2025-09-23 13:34:33 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:34:33 | WARNING | [ORDER][REJECT] LINEAUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:34:33 | WARNING | [ENTER][POSTONLY][FAIL] LINEAUSDT side=Sell qty=7378.0
2025-09-23 13:34:33 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:34:33 | ERROR | [MONITOR][ERR] set_stop_with_retry() got an unexpected keyword argument 'close_side'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 872, in monitor_loop
    set_stop_with_retry(sym, sl_price=sl, tp_price=tp3, close_side=close_side)
TypeError: set_stop_with_retry() got an unexpected keyword argument 'close_side'
2025-09-23 13:34:35 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:34:35 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:34:35 | ERROR | [MONITOR][ERR] set_stop_with_retry() got an unexpected keyword argument 'close_side'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 872, in monitor_loop
    set_stop_with_retry(sym, sl_price=sl, tp_price=tp3, close_side=close_side)
TypeError: set_stop_with_retry() got an unexpected keyword argument 'close_side'
2025-09-23 13:34:38 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:34:38 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:34:38 | ERROR | [MONITOR][ERR] set_stop_with_retry() got an unexpected keyword argument 'close_side'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 872, in monitor_loop
    set_stop_with_retry(sym, sl_price=sl, tp_price=tp3, close_side=close_side)
TypeError: set_stop_with_retry() got an unexpected keyword argument 'close_side'
2025-09-23 13:34:40 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:34:40 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:34:40 | ERROR | [MONITOR][ERR] set_stop_with_retry() got an unexpected keyword argument 'close_side'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 872, in monitor_loop
    set_stop_with_retry(sym, sl_price=sl, tp_price=tp3, close_side=close_side)
TypeError: set_stop_with_retry() got an unexpected keyword argument 'close_side'
2025-09-23 13:34:40 | INFO | [ENTER][PREP] AIAUSDT side=Sell conf=1.00 mid=0.292760 qty=675.0
2025-09-23 13:34:40 | INFO | [ENTER][PREP] STBLUSDT side=Buy conf=1.00 mid=0.339115 qty=583.0
2025-09-23 13:34:40 | INFO | [ENTER][PREP] ASTERUSDT side=Buy conf=1.00 mid=1.602850 qty=124.0
2025-09-23 13:34:40 | WARNING | [ORDER][REJECT] AIAUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:34:40 | WARNING | [ENTER][POSTONLY][FAIL] AIAUSDT side=Sell qty=675.0
2025-09-23 13:34:40 | INFO | [ENTER][PREP] LINEAUSDT side=Sell conf=1.00 mid=0.026805 qty=7373.0
2025-09-23 13:34:40 | INFO | [ENTER][PREP] UBUSDT side=Sell conf=1.00 mid=0.033681 qty=5868.0
2025-09-23 13:34:41 | WARNING | [ORDER][REJECT] STBLUSDT Buy -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:34:41 | WARNING | [ENTER][POSTONLY][FAIL] STBLUSDT side=Buy qty=583.0
2025-09-23 13:34:41 | WARNING | [ORDER][REJECT] ASTERUSDT Buy -> Margin is insufficient.
2025-09-23 13:34:41 | WARNING | [ENTER][POSTONLY][FAIL] ASTERUSDT side=Buy qty=124.0
2025-09-23 13:34:41 | WARNING | [ORDER][REJECT] LINEAUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:34:41 | WARNING | [ENTER][POSTONLY][FAIL] LINEAUSDT side=Sell qty=7373.0
2025-09-23 13:34:41 | WARNING | [ORDER][REJECT] UBUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:34:41 | WARNING | [ENTER][POSTONLY][FAIL] UBUSDT side=Sell qty=5868.0
2025-09-23 13:34:42 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:34:42 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:34:42 | ERROR | [MONITOR][ERR] set_stop_with_retry() got an unexpected keyword argument 'close_side'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 872, in monitor_loop
    set_stop_with_retry(sym, sl_price=sl, tp_price=tp3, close_side=close_side)
TypeError: set_stop_with_retry() got an unexpected keyword argument 'close_side'
2025-09-23 13:34:44 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:34:44 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:34:44 | ERROR | [MONITOR][ERR] set_stop_with_retry() got an unexpected keyword argument 'close_side'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 872, in monitor_loop
    set_stop_with_retry(sym, sl_price=sl, tp_price=tp3, close_side=close_side)
TypeError: set_stop_with_retry() got an unexpected keyword argument 'close_side'
2025-09-23 13:34:46 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:34:47 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:34:47 | ERROR | [MONITOR][ERR] set_stop_with_retry() got an unexpected keyword argument 'close_side'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 872, in monitor_loop
    set_stop_with_retry(sym, sl_price=sl, tp_price=tp3, close_side=close_side)
TypeError: set_stop_with_retry() got an unexpected keyword argument 'close_side'
2025-09-23 13:34:49 | INFO | [ENTER][PREP] ASTERUSDT side=Buy conf=1.00 mid=1.604600 qty=124.0
2025-09-23 13:34:49 | INFO | [ENTER][PREP] UBUSDT side=Sell conf=1.00 mid=0.033702 qty=5864.0
2025-09-23 13:34:49 | INFO | [ENTER][PREP] AIAUSDT side=Sell conf=1.00 mid=0.292605 qty=676.0
2025-09-23 13:34:49 | INFO | [ENTER][PREP] STBLUSDT side=Buy conf=1.00 mid=0.338865 qty=584.0
2025-09-23 13:34:49 | INFO | [ENTER][PREP] LINEAUSDT side=Sell conf=1.00 mid=0.026795 qty=7375.0
2025-09-23 13:34:49 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:34:49 | WARNING | [ORDER][REJECT] ASTERUSDT Buy -> Margin is insufficient.
2025-09-23 13:34:49 | WARNING | [ENTER][POSTONLY][FAIL] ASTERUSDT side=Buy qty=124.0
2025-09-23 13:34:49 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:34:49 | ERROR | [MONITOR][ERR] set_stop_with_retry() got an unexpected keyword argument 'close_side'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 872, in monitor_loop
    set_stop_with_retry(sym, sl_price=sl, tp_price=tp3, close_side=close_side)
TypeError: set_stop_with_retry() got an unexpected keyword argument 'close_side'
2025-09-23 13:34:49 | WARNING | [ORDER][REJECT] UBUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:34:49 | WARNING | [ENTER][POSTONLY][FAIL] UBUSDT side=Sell qty=5864.0
2025-09-23 13:34:49 | WARNING | [ORDER][REJECT] AIAUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:34:49 | WARNING | [ENTER][POSTONLY][FAIL] AIAUSDT side=Sell qty=676.0
2025-09-23 13:34:49 | WARNING | [ORDER][REJECT] STBLUSDT Buy -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:34:49 | WARNING | [ENTER][POSTONLY][FAIL] STBLUSDT side=Buy qty=584.0
2025-09-23 13:34:50 | WARNING | [ORDER][REJECT] LINEAUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:34:50 | WARNING | [ENTER][POSTONLY][FAIL] LINEAUSDT side=Sell qty=7375.0
2025-09-23 13:34:51 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:34:51 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:34:51 | ERROR | [MONITOR][ERR] set_stop_with_retry() got an unexpected keyword argument 'close_side'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 872, in monitor_loop
    set_stop_with_retry(sym, sl_price=sl, tp_price=tp3, close_side=close_side)
TypeError: set_stop_with_retry() got an unexpected keyword argument 'close_side'
2025-09-23 13:34:53 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:34:53 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:34:53 | ERROR | [MONITOR][ERR] set_stop_with_retry() got an unexpected keyword argument 'close_side'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 872, in monitor_loop
    set_stop_with_retry(sym, sl_price=sl, tp_price=tp3, close_side=close_side)
TypeError: set_stop_with_retry() got an unexpected keyword argument 'close_side'
2025-09-23 13:34:55 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:34:55 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:34:55 | ERROR | [MONITOR][ERR] set_stop_with_retry() got an unexpected keyword argument 'close_side'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 872, in monitor_loop
    set_stop_with_retry(sym, sl_price=sl, tp_price=tp3, close_side=close_side)
TypeError: set_stop_with_retry() got an unexpected keyword argument 'close_side'
2025-09-23 13:34:57 | INFO | [ENTER][PREP] AIAUSDT side=Sell conf=1.00 mid=0.292770 qty=675.0
2025-09-23 13:34:57 | INFO | [ENTER][PREP] LINEAUSDT side=Sell conf=1.00 mid=0.026825 qty=7367.0
2025-09-23 13:34:57 | INFO | [ENTER][PREP] UBUSDT side=Sell conf=1.00 mid=0.033667 qty=5870.0
2025-09-23 13:34:57 | INFO | [ENTER][PREP] STBLUSDT side=Buy conf=1.00 mid=0.339165 qty=583.0
2025-09-23 13:34:57 | INFO | [ENTER][PREP] ASTERUSDT side=Buy conf=1.00 mid=1.602650 qty=124.0
2025-09-23 13:34:57 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:34:58 | WARNING | [ORDER][REJECT] AIAUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:34:58 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:34:58 | WARNING | [ENTER][POSTONLY][FAIL] AIAUSDT side=Sell qty=675.0
2025-09-23 13:34:58 | ERROR | [MONITOR][ERR] set_stop_with_retry() got an unexpected keyword argument 'close_side'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 872, in monitor_loop
    set_stop_with_retry(sym, sl_price=sl, tp_price=tp3, close_side=close_side)
TypeError: set_stop_with_retry() got an unexpected keyword argument 'close_side'
2025-09-23 13:34:58 | WARNING | [ORDER][REJECT] LINEAUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:34:58 | WARNING | [ENTER][POSTONLY][FAIL] LINEAUSDT side=Sell qty=7367.0
2025-09-23 13:34:58 | WARNING | [ORDER][REJECT] UBUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:34:58 | WARNING | [ENTER][POSTONLY][FAIL] UBUSDT side=Sell qty=5870.0
2025-09-23 13:34:58 | WARNING | [ORDER][REJECT] STBLUSDT Buy -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:34:58 | WARNING | [ENTER][POSTONLY][FAIL] STBLUSDT side=Buy qty=583.0
2025-09-23 13:34:58 | WARNING | [ORDER][REJECT] ASTERUSDT Buy -> Margin is insufficient.
2025-09-23 13:34:58 | WARNING | [ENTER][POSTONLY][FAIL] ASTERUSDT side=Buy qty=124.0
2025-09-23 13:35:00 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:35:00 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:35:00 | ERROR | [MONITOR][ERR] set_stop_with_retry() got an unexpected keyword argument 'close_side'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 872, in monitor_loop
    set_stop_with_retry(sym, sl_price=sl, tp_price=tp3, close_side=close_side)
TypeError: set_stop_with_retry() got an unexpected keyword argument 'close_side'
2025-09-23 13:35:02 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:35:02 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:35:02 | ERROR | [MONITOR][ERR] set_stop_with_retry() got an unexpected keyword argument 'close_side'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 872, in monitor_loop
    set_stop_with_retry(sym, sl_price=sl, tp_price=tp3, close_side=close_side)
TypeError: set_stop_with_retry() got an unexpected keyword argument 'close_side'
2025-09-23 13:35:04 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:35:04 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:35:04 | ERROR | [MONITOR][ERR] set_stop_with_retry() got an unexpected keyword argument 'close_side'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 872, in monitor_loop
    set_stop_with_retry(sym, sl_price=sl, tp_price=tp3, close_side=close_side)
TypeError: set_stop_with_retry() got an unexpected keyword argument 'close_side'
2025-09-23 13:35:06 | INFO | [ENTER][PREP] LINEAUSDT side=Sell conf=1.00 mid=0.026825 qty=7367.0
2025-09-23 13:35:06 | INFO | [ENTER][PREP] UBUSDT side=Sell conf=1.00 mid=0.033685 qty=5867.0
2025-09-23 13:35:06 | INFO | [ENTER][PREP] AIAUSDT side=Sell conf=1.00 mid=0.293250 qty=674.0
2025-09-23 13:35:06 | INFO | [ENTER][PREP] STBLUSDT side=Buy conf=1.00 mid=0.338855 qty=584.0
2025-09-23 13:35:06 | INFO | [ENTER][PREP] ASTERUSDT side=Buy conf=1.00 mid=1.603800 qty=124.0
2025-09-23 13:35:06 | WARNING | [ORDER][REJECT] LINEAUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:35:06 | WARNING | [ENTER][POSTONLY][FAIL] LINEAUSDT side=Sell qty=7367.0
2025-09-23 13:35:06 | WARNING | [ORDER][REJECT] UBUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:35:06 | WARNING | [ENTER][POSTONLY][FAIL] UBUSDT side=Sell qty=5867.0
2025-09-23 13:35:06 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:35:06 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:35:06 | ERROR | [MONITOR][ERR] set_stop_with_retry() got an unexpected keyword argument 'close_side'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 872, in monitor_loop
    set_stop_with_retry(sym, sl_price=sl, tp_price=tp3, close_side=close_side)
TypeError: set_stop_with_retry() got an unexpected keyword argument 'close_side'
2025-09-23 13:35:06 | WARNING | [ORDER][REJECT] AIAUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:35:06 | WARNING | [ENTER][POSTONLY][FAIL] AIAUSDT side=Sell qty=674.0
2025-09-23 13:35:07 | WARNING | [ORDER][REJECT] STBLUSDT Buy -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:35:07 | WARNING | [ENTER][POSTONLY][FAIL] STBLUSDT side=Buy qty=584.0
2025-09-23 13:35:07 | WARNING | [ORDER][REJECT] ASTERUSDT Buy -> Margin is insufficient.
2025-09-23 13:35:07 | WARNING | [ENTER][POSTONLY][FAIL] ASTERUSDT side=Buy qty=124.0
2025-09-23 13:35:09 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:35:09 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:35:09 | ERROR | [MONITOR][ERR] set_stop_with_retry() got an unexpected keyword argument 'close_side'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 872, in monitor_loop
    set_stop_with_retry(sym, sl_price=sl, tp_price=tp3, close_side=close_side)
TypeError: set_stop_with_retry() got an unexpected keyword argument 'close_side'
2025-09-23 13:35:11 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:35:11 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:35:11 | ERROR | [MONITOR][ERR] set_stop_with_retry() got an unexpected keyword argument 'close_side'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 872, in monitor_loop
    set_stop_with_retry(sym, sl_price=sl, tp_price=tp3, close_side=close_side)
TypeError: set_stop_with_retry() got an unexpected keyword argument 'close_side'
2025-09-23 13:35:13 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:35:13 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:35:13 | ERROR | [MONITOR][ERR] set_stop_with_retry() got an unexpected keyword argument 'close_side'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 872, in monitor_loop
    set_stop_with_retry(sym, sl_price=sl, tp_price=tp3, close_side=close_side)
TypeError: set_stop_with_retry() got an unexpected keyword argument 'close_side'
2025-09-23 13:35:14 | INFO | [ENTER][PREP] AIAUSDT side=Sell conf=1.00 mid=0.293215 qty=674.0
2025-09-23 13:35:14 | INFO | [ENTER][PREP] LINEAUSDT side=Sell conf=1.00 mid=0.026805 qty=7373.0
2025-09-23 13:35:14 | INFO | [ENTER][PREP] ASTERUSDT side=Buy conf=1.00 mid=1.602650 qty=124.0
2025-09-23 13:35:14 | INFO | [ENTER][PREP] STBLUSDT side=Buy conf=1.00 mid=0.337775 qty=586.0
2025-09-23 13:35:14 | INFO | [ENTER][PREP] UBUSDT side=Sell conf=1.00 mid=0.033702 qty=5864.0
2025-09-23 13:35:14 | WARNING | [ORDER][REJECT] AIAUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:35:14 | WARNING | [ENTER][POSTONLY][FAIL] AIAUSDT side=Sell qty=674.0
2025-09-23 13:35:15 | WARNING | [ORDER][REJECT] LINEAUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:35:15 | WARNING | [ENTER][POSTONLY][FAIL] LINEAUSDT side=Sell qty=7373.0
2025-09-23 13:35:15 | WARNING | [ORDER][REJECT] ASTERUSDT Buy -> Margin is insufficient.
2025-09-23 13:35:15 | WARNING | [ENTER][POSTONLY][FAIL] ASTERUSDT side=Buy qty=124.0
2025-09-23 13:35:15 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:35:15 | WARNING | [ORDER][REJECT] STBLUSDT Buy -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:35:15 | WARNING | [ENTER][POSTONLY][FAIL] STBLUSDT side=Buy qty=586.0
2025-09-23 13:35:15 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:35:15 | ERROR | [MONITOR][ERR] set_stop_with_retry() got an unexpected keyword argument 'close_side'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 872, in monitor_loop
    set_stop_with_retry(sym, sl_price=sl, tp_price=tp3, close_side=close_side)
TypeError: set_stop_with_retry() got an unexpected keyword argument 'close_side'
2025-09-23 13:35:15 | WARNING | [ORDER][REJECT] UBUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:35:15 | WARNING | [ENTER][POSTONLY][FAIL] UBUSDT side=Sell qty=5864.0
2025-09-23 13:35:17 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:35:17 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:35:17 | ERROR | [MONITOR][ERR] set_stop_with_retry() got an unexpected keyword argument 'close_side'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 872, in monitor_loop
    set_stop_with_retry(sym, sl_price=sl, tp_price=tp3, close_side=close_side)
TypeError: set_stop_with_retry() got an unexpected keyword argument 'close_side'
2025-09-23 13:35:19 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:35:19 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:35:19 | ERROR | [MONITOR][ERR] set_stop_with_retry() got an unexpected keyword argument 'close_side'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 872, in monitor_loop
    set_stop_with_retry(sym, sl_price=sl, tp_price=tp3, close_side=close_side)
TypeError: set_stop_with_retry() got an unexpected keyword argument 'close_side'
2025-09-23 13:35:22 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:35:22 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:35:22 | ERROR | [MONITOR][ERR] set_stop_with_retry() got an unexpected keyword argument 'close_side'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 872, in monitor_loop
    set_stop_with_retry(sym, sl_price=sl, tp_price=tp3, close_side=close_side)
TypeError: set_stop_with_retry() got an unexpected keyword argument 'close_side'
2025-09-23 13:35:23 | INFO | [ENTER][PREP] ASTERUSDT side=Buy conf=1.00 mid=1.603250 qty=124.0
2025-09-23 13:35:23 | INFO | [ENTER][PREP] AIAUSDT side=Sell conf=1.00 mid=0.293415 qty=674.0
2025-09-23 13:35:23 | INFO | [ENTER][PREP] STBLUSDT side=Buy conf=1.00 mid=0.337680 qty=586.0
2025-09-23 13:35:23 | INFO | [ENTER][PREP] UBUSDT side=Sell conf=1.00 mid=0.033736 qty=5858.0
2025-09-23 13:35:23 | INFO | [ENTER][PREP] LINEAUSDT side=Sell conf=1.00 mid=0.026815 qty=7370.0
2025-09-23 13:35:23 | WARNING | [ORDER][REJECT] ASTERUSDT Buy -> Margin is insufficient.
2025-09-23 13:35:23 | WARNING | [ENTER][POSTONLY][FAIL] ASTERUSDT side=Buy qty=124.0
2025-09-23 13:35:24 | WARNING | [ORDER][REJECT] AIAUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:35:24 | WARNING | [ENTER][POSTONLY][FAIL] AIAUSDT side=Sell qty=674.0
2025-09-23 13:35:24 | WARNING | [ORDER][REJECT] STBLUSDT Buy -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:35:24 | WARNING | [ENTER][POSTONLY][FAIL] STBLUSDT side=Buy qty=586.0
2025-09-23 13:35:24 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:35:24 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:35:24 | ERROR | [MONITOR][ERR] set_stop_with_retry() got an unexpected keyword argument 'close_side'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 872, in monitor_loop
    set_stop_with_retry(sym, sl_price=sl, tp_price=tp3, close_side=close_side)
TypeError: set_stop_with_retry() got an unexpected keyword argument 'close_side'
2025-09-23 13:35:24 | WARNING | [ORDER][REJECT] UBUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:35:24 | WARNING | [ENTER][POSTONLY][FAIL] UBUSDT side=Sell qty=5858.0
2025-09-23 13:35:24 | WARNING | [ORDER][REJECT] LINEAUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:35:24 | WARNING | [ENTER][POSTONLY][FAIL] LINEAUSDT side=Sell qty=7370.0
2025-09-23 13:35:26 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:35:26 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:35:26 | ERROR | [MONITOR][ERR] set_stop_with_retry() got an unexpected keyword argument 'close_side'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 872, in monitor_loop
    set_stop_with_retry(sym, sl_price=sl, tp_price=tp3, close_side=close_side)
TypeError: set_stop_with_retry() got an unexpected keyword argument 'close_side'
2025-09-23 13:35:28 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:35:28 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:35:28 | ERROR | [MONITOR][ERR] set_stop_with_retry() got an unexpected keyword argument 'close_side'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 872, in monitor_loop
    set_stop_with_retry(sym, sl_price=sl, tp_price=tp3, close_side=close_side)
TypeError: set_stop_with_retry() got an unexpected keyword argument 'close_side'
2025-09-23 13:35:30 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:35:30 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:35:30 | ERROR | [MONITOR][ERR] set_stop_with_retry() got an unexpected keyword argument 'close_side'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 872, in monitor_loop
    set_stop_with_retry(sym, sl_price=sl, tp_price=tp3, close_side=close_side)
TypeError: set_stop_with_retry() got an unexpected keyword argument 'close_side'
2025-09-23 13:35:32 | INFO | [ENTER][PREP] LINEAUSDT side=Sell conf=1.00 mid=0.026785 qty=7378.0
2025-09-23 13:35:32 | INFO | [ENTER][PREP] STBLUSDT side=Buy conf=1.00 mid=0.337130 qty=587.0
2025-09-23 13:35:32 | INFO | [ENTER][PREP] ASTERUSDT side=Buy conf=1.00 mid=1.603450 qty=124.0
2025-09-23 13:35:32 | INFO | [ENTER][PREP] UBUSDT side=Sell conf=1.00 mid=0.033722 qty=5860.0
2025-09-23 13:35:32 | INFO | [ENTER][PREP] AIAUSDT side=Sell conf=1.00 mid=0.293065 qty=675.0
2025-09-23 13:35:32 | WARNING | [ORDER][REJECT] LINEAUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:35:32 | WARNING | [ENTER][POSTONLY][FAIL] LINEAUSDT side=Sell qty=7378.0
2025-09-23 13:35:32 | WARNING | [ORDER][REJECT] STBLUSDT Buy -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:35:32 | WARNING | [ENTER][POSTONLY][FAIL] STBLUSDT side=Buy qty=587.0
2025-09-23 13:35:32 | WARNING | [ORDER][REJECT] ASTERUSDT Buy -> Margin is insufficient.
2025-09-23 13:35:32 | WARNING | [ENTER][POSTONLY][FAIL] ASTERUSDT side=Buy qty=124.0
2025-09-23 13:35:33 | WARNING | [ORDER][REJECT] UBUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:35:33 | WARNING | [ENTER][POSTONLY][FAIL] UBUSDT side=Sell qty=5860.0
2025-09-23 13:35:33 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:35:33 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:35:33 | ERROR | [MONITOR][ERR] set_stop_with_retry() got an unexpected keyword argument 'close_side'
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 872, in monitor_loop
    set_stop_with_retry(sym, sl_price=sl, tp_price=tp3, close_side=close_side)
TypeError: set_stop_with_retry() got an unexpected keyword argument 'close_side'
2025-09-23 13:35:33 | WARNING | [ORDER][REJECT] AIAUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:35:33 | WARNING | [ENTER][POSTONLY][FAIL] AIAUSDT side=Sell qty=675.0
2025-09-23 13:35:38 | INFO | === Logger initialized ===
2025-09-23 13:35:38 | INFO | [MONITOR][START] poll=1.0s
2025-09-23 13:35:38 | INFO | [SCANNER][START] delay=2.5s parallel=True workers=6
2025-09-23 13:35:39 | WARNING | [ORDER][REJECT] BARDUSDT Sell -> Due to the order could not be executed as maker, the Post Only order will be rejected. The order will not be recorded in the order history
2025-09-23 13:35:39 | INFO | [MONITOR][NEWPOS] BARDUSDT Buy qty=193.0 entry=1.023900
2025-09-23 13:35:39 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:35:39 | WARNING | [ORDER][REJECT] SOMIUSDT Buy -> ReduceOnly Order is rejected.
2025-09-23 13:35:39 | INFO | [MONITOR][NEWPOS] SOMIUSDT Sell qty=219.0 entry=0.900000
2025-09-23 13:35:39 | INFO | [MONITOR][NEWPOS] OPENUSDT Sell qty=274.0 entry=0.719700
2025-09-23 13:35:39 | WARNING | [ORDER][REJECT] 0GUSDT Sell -> Due to the order could not be executed as maker, the Post Only order will be rejected. The order will not be recorded in the order history
2025-09-23 13:35:40 | INFO | [MONITOR][NEWPOS] 0GUSDT Buy qty=33.0 entry=6.004400
2025-09-23 13:35:44 | INFO | [ENTER][PREP] ASTERUSDT side=Buy conf=1.00 mid=1.599650 qty=124.0
2025-09-23 13:35:44 | WARNING | [ORDER][REJECT] ASTERUSDT Buy -> Margin is insufficient.
2025-09-23 13:35:44 | WARNING | [ENTER][POSTONLY][FAIL] ASTERUSDT side=Buy qty=124.0
2025-09-23 13:35:44 | INFO | [ENTER][PREP] AIAUSDT side=Sell conf=1.00 mid=0.293015 qty=675.0
2025-09-23 13:35:44 | INFO | [ENTER][PREP] LINEAUSDT side=Sell conf=1.00 mid=0.026785 qty=7378.0
2025-09-23 13:35:44 | INFO | [ENTER][PREP] UBUSDT side=Sell conf=1.00 mid=0.033763 qty=5853.0
2025-09-23 13:35:44 | INFO | [ENTER][PREP] STBLUSDT side=Buy conf=1.00 mid=0.338025 qty=585.0
2025-09-23 13:35:45 | WARNING | [ORDER][REJECT] AIAUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:35:45 | WARNING | [ENTER][POSTONLY][FAIL] AIAUSDT side=Sell qty=675.0
2025-09-23 13:35:45 | WARNING | [ORDER][REJECT] LINEAUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:35:45 | WARNING | [ENTER][POSTONLY][FAIL] LINEAUSDT side=Sell qty=7378.0
2025-09-23 13:35:45 | WARNING | [ORDER][REJECT] UBUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:35:45 | WARNING | [ENTER][POSTONLY][FAIL] UBUSDT side=Sell qty=5853.0
2025-09-23 13:35:45 | WARNING | [ORDER][REJECT] STBLUSDT Buy -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:35:45 | WARNING | [ENTER][POSTONLY][FAIL] STBLUSDT side=Buy qty=585.0
2025-09-23 13:35:53 | INFO | [ENTER][PREP] AIAUSDT side=Sell conf=1.00 mid=0.293130 qty=675.0
2025-09-23 13:35:53 | INFO | [ENTER][PREP] ASTERUSDT side=Buy conf=1.00 mid=1.597550 qty=124.0
2025-09-23 13:35:53 | INFO | [ENTER][PREP] STBLUSDT side=Buy conf=1.00 mid=0.337805 qty=585.0
2025-09-23 13:35:53 | INFO | [ENTER][PREP] LINEAUSDT side=Sell conf=1.00 mid=0.026765 qty=7384.0
2025-09-23 13:35:53 | INFO | [ENTER][PREP] UBUSDT side=Sell conf=1.00 mid=0.033734 qty=5858.0
2025-09-23 13:35:53 | WARNING | [ORDER][REJECT] AIAUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:35:53 | WARNING | [ENTER][POSTONLY][FAIL] AIAUSDT side=Sell qty=675.0
2025-09-23 13:35:53 | INFO | [ENTER][POSTONLY] ASTERUSDT side=Buy qty=124.0 px=1.5974000000000002 oid=247273003
2025-09-23 13:35:53 | WARNING | [ORDER][REJECT] STBLUSDT Buy -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:35:53 | WARNING | [ENTER][POSTONLY][FAIL] STBLUSDT side=Buy qty=585.0
2025-09-23 13:35:54 | INFO | [POSTONLY][FILLED/REMOVED] ASTERUSDT oid=247273003
2025-09-23 13:35:54 | INFO | [MONITOR][NEWPOS] ASTERUSDT Buy qty=124.0 entry=1.597400
2025-09-23 13:35:55 | ERROR | [MONITOR][ERR] APIError(code=-1003): Too many requests; current limit of IP(58.227.45.207) is 2400 requests per minute. Please use the websocket for live updates to avoid polling the API.
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 916, in monitor_loop
    _update_trailing_and_be(sym)
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 787, in _update_trailing_and_be
    st=STATE.get(symbol); pos=get_positions().get(symbol)
                              ^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 152, in get_positions
    lst = client.futures_position_information()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\torch311\Lib\site-packages\binance\client.py", line 7835, in futures_position_information
    return self._request_futures_api("get", "positionRisk", True, 3, data=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\torch311\Lib\site-packages\binance\client.py", line 126, in _request_futures_api
    return self._request(method, uri, signed, force_params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\torch311\Lib\site-packages\binance\client.py", line 89, in _request
    return self._handle_response(self.response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\torch311\Lib\site-packages\binance\client.py", line 98, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1003): Too many requests; current limit of IP(58.227.45.207) is 2400 requests per minute. Please use the websocket for live updates to avoid polling the API.
2025-09-23 13:35:56 | ERROR | [SCANNER][ERR] APIError(code=-1003): Too many requests; current limit of IP(58.227.45.207) is 2400 requests per minute. Please use the websocket for live updates to avoid polling the API.
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 864, in scanner_loop
    try:
         
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 152, in get_positions
    lst = client.futures_position_information()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\torch311\Lib\site-packages\binance\client.py", line 7835, in futures_position_information
    return self._request_futures_api("get", "positionRisk", True, 3, data=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\torch311\Lib\site-packages\binance\client.py", line 126, in _request_futures_api
    return self._request(method, uri, signed, force_params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\torch311\Lib\site-packages\binance\client.py", line 89, in _request
    return self._handle_response(self.response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\torch311\Lib\site-packages\binance\client.py", line 98, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1003): Too many requests; current limit of IP(58.227.45.207) is 2400 requests per minute. Please use the websocket for live updates to avoid polling the API.
2025-09-23 13:35:57 | ERROR | [MONITOR][ERR] APIError(code=-1003): Too many requests; current limit of IP(58.227.45.207) is 2400 requests per minute. Please use the websocket for live updates to avoid polling the API.
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 882, in monitor_loop
    _log_equity(get_wallet_equity())
          ^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 152, in get_positions
    lst = client.futures_position_information()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\torch311\Lib\site-packages\binance\client.py", line 7835, in futures_position_information
    return self._request_futures_api("get", "positionRisk", True, 3, data=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\torch311\Lib\site-packages\binance\client.py", line 126, in _request_futures_api
    return self._request(method, uri, signed, force_params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\torch311\Lib\site-packages\binance\client.py", line 89, in _request
    return self._handle_response(self.response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\torch311\Lib\site-packages\binance\client.py", line 98, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1003): Too many requests; current limit of IP(58.227.45.207) is 2400 requests per minute. Please use the websocket for live updates to avoid polling the API.
2025-09-23 13:35:58 | ERROR | [SCANNER][ERR] APIError(code=-1003): Too many requests; current limit of IP(58.227.45.207) is 2400 requests per minute. Please use the websocket for live updates to avoid polling the API.
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 864, in scanner_loop
    try:
         
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 152, in get_positions
    lst = client.futures_position_information()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\torch311\Lib\site-packages\binance\client.py", line 7835, in futures_position_information
    return self._request_futures_api("get", "positionRisk", True, 3, data=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\torch311\Lib\site-packages\binance\client.py", line 126, in _request_futures_api
    return self._request(method, uri, signed, force_params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\torch311\Lib\site-packages\binance\client.py", line 89, in _request
    return self._handle_response(self.response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\torch311\Lib\site-packages\binance\client.py", line 98, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1003): Too many requests; current limit of IP(58.227.45.207) is 2400 requests per minute. Please use the websocket for live updates to avoid polling the API.
2025-09-23 13:35:59 | ERROR | [MONITOR][ERR] APIError(code=-1003): Too many requests; current limit of IP(58.227.45.207) is 2400 requests per minute. Please use the websocket for live updates to avoid polling the API.
Traceback (most recent call last):
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 882, in monitor_loop
    _log_equity(get_wallet_equity())
          ^^^^^^^^^^^^^^^
  File "D:\ygy_work\coin\multimodel\binace_autotrade_tcn.py", line 152, in get_positions
    lst = client.futures_position_information()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\torch311\Lib\site-packages\binance\client.py", line 7835, in futures_position_information
    return self._request_futures_api("get", "positionRisk", True, 3, data=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\torch311\Lib\site-packages\binance\client.py", line 126, in _request_futures_api
    return self._request(method, uri, signed, force_params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\torch311\Lib\site-packages\binance\client.py", line 89, in _request
    return self._handle_response(self.response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\torch311\Lib\site-packages\binance\client.py", line 98, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1003): Too many requests; current limit of IP(58.227.45.207) is 2400 requests per minute. Please use the websocket for live updates to avoid polling the API.
2025-09-23 13:36:01 | INFO | [MONITOR][NEWPOS] ASTERUSDT Buy qty=124.0 entry=1.597400
2025-09-23 13:36:27 | INFO | === Logger initialized ===
2025-09-23 13:36:27 | INFO | [MONITOR][START] poll=1.0s
2025-09-23 13:36:27 | INFO | [SCANNER][START] delay=2.5s parallel=True workers=6
2025-09-23 13:36:28 | INFO | [MONITOR][NEWPOS] BARDUSDT Buy qty=193.0 entry=1.023900
2025-09-23 13:36:28 | INFO | [MONITOR][NEWPOS] 0GUSDT Buy qty=33.0 entry=6.004400
2025-09-23 13:36:28 | INFO | [MONITOR][NEWPOS] OPENUSDT Sell qty=274.0 entry=0.719700
2025-09-23 13:36:28 | INFO | [MONITOR][NEWPOS] ASTERUSDT Buy qty=124.0 entry=1.597400
2025-09-23 13:36:28 | INFO | [MONITOR][NEWPOS] SOMIUSDT Sell qty=219.0 entry=0.900000
2025-09-23 13:37:12 | INFO | [MONITOR][CLOSED] ASTERUSDT
2025-09-23 13:37:17 | INFO | [ENTER][PREP] AIAUSDT side=Sell conf=1.00 mid=0.293670 qty=677.0
2025-09-23 13:37:18 | INFO | [ENTER][PREP] LINEAUSDT side=Sell conf=1.00 mid=0.026975 qty=7370.0
2025-09-23 13:37:18 | INFO | [ENTER][PREP] UBUSDT side=Sell conf=1.00 mid=0.033560 qty=5924.0
2025-09-23 13:37:18 | INFO | [ENTER][PREP] STBLUSDT side=Buy conf=1.00 mid=0.335300 qty=593.0
2025-09-23 13:37:18 | WARNING | [ORDER][REJECT] AIAUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:37:18 | WARNING | [ENTER][POSTONLY][FAIL] AIAUSDT side=Sell qty=677.0
2025-09-23 13:37:18 | WARNING | [ORDER][REJECT] LINEAUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:37:18 | WARNING | [ENTER][POSTONLY][FAIL] LINEAUSDT side=Sell qty=7370.0
2025-09-23 13:37:18 | WARNING | [ORDER][REJECT] UBUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:37:18 | WARNING | [ENTER][POSTONLY][FAIL] UBUSDT side=Sell qty=5924.0
2025-09-23 13:37:18 | WARNING | [ORDER][REJECT] STBLUSDT Buy -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:37:18 | WARNING | [ENTER][POSTONLY][FAIL] STBLUSDT side=Buy qty=593.0
2025-09-23 13:37:25 | INFO | [ENTER][PREP] AIAUSDT side=Sell conf=1.00 mid=0.293745 qty=677.0
2025-09-23 13:37:25 | INFO | [ENTER][PREP] UBUSDT side=Sell conf=1.00 mid=0.033594 qty=5918.0
2025-09-23 13:37:25 | INFO | [ENTER][PREP] STBLUSDT side=Buy conf=1.00 mid=0.335110 qty=594.0
2025-09-23 13:37:25 | INFO | [ENTER][PREP] LINEAUSDT side=Sell conf=1.00 mid=0.026985 qty=7367.0
2025-09-23 13:37:25 | WARNING | [ORDER][REJECT] AIAUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:37:25 | WARNING | [ENTER][POSTONLY][FAIL] AIAUSDT side=Sell qty=677.0
2025-09-23 13:37:25 | WARNING | [ORDER][REJECT] UBUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:37:25 | WARNING | [ENTER][POSTONLY][FAIL] UBUSDT side=Sell qty=5918.0
2025-09-23 13:37:25 | WARNING | [ORDER][REJECT] STBLUSDT Buy -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:37:25 | WARNING | [ENTER][POSTONLY][FAIL] STBLUSDT side=Buy qty=594.0
2025-09-23 13:37:26 | WARNING | [ORDER][REJECT] LINEAUSDT Sell -> Mandatory parameter 'price' was not sent, was empty/null, or malformed.
2025-09-23 13:37:26 | WARNING | [ENTER][POSTONLY][FAIL] LINEAUSDT side=Sell qty=7367.0
